Configure workload identity
wso2/azure-terraform-modules pull request #25
Opened 2024-01-22 11:35 UTC by SulakshanaBandara

2024-01-22 11:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/azure-terraform-modules?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/azure-terraform-modules?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/azure-terraform-modules?pullRequest=25) it.</sub>

2024-01-22 12:55 UTC, Uvindu96 commented on modules/azurerm/AKS-Firewall/aks_cluster.tf
> +  workload_identity_enabled           = true
better to parameterize these values

2024-01-22 12:56 UTC, Uvindu96 commented on modules/azurerm/Federated-Identity/Federated-Credentials.tf
> +}
need a new line here

2024-01-23 05:13 UTC, ayeshajay requested changes

2024-01-23 05:13 UTC, ayeshajay commented on modules/azurerm/AKS-Firewall/variables.tf
> +}
Add a new line

2024-01-23 05:13 UTC, ayeshajay commented on modules/azurerm/Federated-Identity/Federated-Credentials.tf
> +
remove unwanted new line

2024-01-23 05:13 UTC, ayeshajay commented on modules/azurerm/Key-Vault-Access-Policy/variables.tf
> +variable "" {}
Do we need this?

2024-01-23 06:30 UTC, Migara-Pramod requested changes

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/AKS-Firewall/variables.tf
> +  type        = bool
Set a default value to false.

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/AKS-Firewall/variables.tf
> +  type        = bool
Set default value to false

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/Federated-Identity/Federated-Credentials.tf
> +resource "azurerm_federated_identity_credential" "federated_credentials_name" {
```suggestion
resource "azurerm_federated_identity_credential" "federated_credentials" {
```

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/Federated-Identity/Federated-Credentials.tf
> +  audience            = ["api://AzureADTokenExchange"]
Why we hardcode the audience

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/Federated-Identity/Federated-Credentials.tf
> +  subject             = "system:serviceaccount:${workload_sa_namespace}:${workload_sa_name}"
Shall we get this from a variable as well

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/Federated-Identity/variables.tf
> +  description = "AKS cluster name"
Change this

2024-01-23 06:30 UTC, Migara-Pramod commented on modules/azurerm/Federated-Identity/variables.tf
> +  description = "OIDC Url"
```suggestion
  description = "OIDC issuer url"
```

2024-01-23 09:04 UTC, Migara-Pramod requested changes

2024-02-16 09:40 UTC, closed without merging