Integrate workload identity
wso2/azure-terraform-modules pull request #29
Opened 2024-01-31 04:20 UTC by SulakshanaBandara

Description:

- Update the AKS (Azure Kubernetes Service) cluster and configuring federated identities. The goal is to integrate Azure AD Workload Identity.

Changes made:

- Integrate a new resource as Federated_identity_credentials.
- Updated the AKS cluster by enabling workload identity in the AKS cluster
- Updated the AKS cluster by enabling OIDC url in the AKS cluster.

Related GIT issue:
[https://github.com/wso2-enterprise/iam-engineering/issues/863](https://github.com/wso2-enterprise/iam-engineering/issues/863)

2024-01-31 05:50 UTC, ThilinaManamgoda requested changes

2024-01-31 05:50 UTC, ThilinaManamgoda commented on modules/azurerm/Federated-Identity/variables.tf
> +variable "workload_sa_name" {
Shall we stick to `subject` as this module is generic. Value passed for the subject can be service account or else that is up to the end user.

2024-01-31 05:50 UTC, ThilinaManamgoda commented on modules/azurerm/Federated-Identity/variables.tf
> +  description = "federated credential audience"
Let's stick to `audience` with description `Audience for this Federated Identity Credential`

2024-01-31 05:50 UTC, ThilinaManamgoda commented on modules/azurerm/Federated-Identity/variables.tf
> +  type        = list(any)
Shouldn't it be `list(string)`

2024-01-31 05:50 UTC, ThilinaManamgoda commented on modules/azurerm/Federated-Identity/variables.tf
> +  description = "AKS cluster name"
Let's stick to `name` and generic description `Name of this Federated Identity Credential`.

2024-01-31 05:50 UTC, ThilinaManamgoda commented on modules/azurerm/Federated-Identity/variables.tf
> +  description = "AKS cluster name"
Have we looked what is the abbreviation for  Federated Identity Credential ?

2024-01-31 05:50 UTC, ThilinaManamgoda commented on modules/azurerm/Federated-Identity/versions.tf
> +      version = ">= 3.0.0"
Does this support `>= 3.52.0` ?

2024-02-01 04:49 UTC, ThilinaManamgoda approved these changes

2024-02-01 04:49 UTC, ThilinaManamgoda requested changes

2024-02-01 04:49 UTC, ThilinaManamgoda commented on .idea/$PROJECT_FILE$
> +<?xml version="1.0" encoding="UTF-8"?>
Let's remove this file

2024-02-01 04:55 UTC, ThilinaManamgoda approved these changes

2024-02-01 05:36 UTC, Migara-Pramod approved these changes

2024-02-01 05:37 UTC, merged